# Generated by Django 2.2 on 2021-08-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='expert_name',
            field=models.CharField(default='name', max_length=256),
        ),
    ]
