# Generated by Django 2.2 on 2021-08-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_expert_expert_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='profile_pic',
        ),
    ]
