# Generated by Django 2.2 on 2021-08-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_remove_expert_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='profile_pic',
            field=models.ImageField(default='profilepic.jpg', upload_to='media'),
        ),
    ]
