# Generated by Django 2.2 on 2021-05-20 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profilepic.jpg', upload_to='media')),
                ('description', models.TextField()),
                ('myposts', models.CharField(blank=True, max_length=300, null=True)),
                ('my_bookmarks', models.CharField(blank=True, max_length=300, null=True)),
                ('my_paymentdetails', models.CharField(blank=True, max_length=300, null=True)),
                ('my_wishlist', models.CharField(blank=True, max_length=300, null=True)),
                ('my_scores', models.IntegerField(blank=True, null=True)),
                ('my_itemsview', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
