# Generated by Django 2.2 on 2021-05-19 12:17

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('item_description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='media')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, default='https://www.youtube.com/watch?v=l3wwoOEYPuI')),
                ('item_article', models.FileField(upload_to='media')),
                ('article_type', models.CharField(default=None, max_length=100)),
                ('topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contentpiece.Category')),
            ],
        ),
    ]
