# Generated by Django 2.2 on 2021-05-21 01:31

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0002_item_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='video',
        ),
        migrations.AddField(
            model_name='item',
            name='articlelink',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=J3MuH6xaDjI&t=493s'),
        ),
        migrations.AlterField(
            model_name='item',
            name='article_type',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_article',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
