# Generated by Django 2.2 on 2021-05-21 01:46

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0003_auto_20210521_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='articlelink',
            field=embed_video.fields.EmbedVideoField(blank=True, default='https://www.youtube.com/watch?v=J3MuH6xaDjI&t=493s'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_article',
            field=models.FileField(upload_to='media'),
        ),
    ]
