# Generated by Django 2.2 on 2021-05-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0004_auto_20210521_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(default='c.png', upload_to='media'),
        ),
    ]
