# Generated by Django 2.2 on 2021-05-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0005_auto_20210521_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='articlelink',
        ),
    ]
