# Generated by Django 2.2 on 2021-05-21 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0007_auto_20210521_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(max_length=500),
        ),
    ]
