# Generated by Django 2.2 on 2021-05-22 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentpiece', '0009_auto_20210522_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
