# Generated by Django 2.2 on 2021-05-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0015_auto_20210524_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
