# Generated by Django 2.2 on 2021-05-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0017_auto_20210524_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='language_of_instruction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
