# Generated by Django 2.2 on 2021-05-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0018_item_language_of_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='language_of_instruction',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
