# Generated by Django 2.2 on 2021-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0020_auto_20210530_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='language_of_instruction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
