# Generated by Django 2.2 on 2021-07-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0022_auto_20210623_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_name', models.CharField(max_length=50)),
            ],
        ),
    ]
