# Generated by Django 2.2 on 2021-06-29 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0023_pricecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_cost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contentpiece.PriceCategory'),
        ),
    ]
