# Generated by Django 2.2 on 2021-07-08 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0023_price_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_pricecategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contentpiece.Price_Category'),
        ),
    ]
