# Generated by Django 2.2 on 2021-07-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0024_item_item_pricecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_viewcount',
            field=models.IntegerField(default=1),
        ),
    ]
