# Generated by Django 2.2 on 2021-08-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0026_auto_20210716_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='language_of_instruction',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
