# Generated by Django 2.2 on 2021-08-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0027_auto_20210801_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_viewcount',
            field=models.IntegerField(default=1),
        ),
    ]
