# Generated by Django 2.2 on 2021-08-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0029_langinstr'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='loi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contentpiece.Langinstr'),
        ),
    ]
