# Generated by Django 2.2 on 2021-08-20 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0029_lofist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lofi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contentpiece.Lofist'),
        ),
    ]
