# Generated by Django 2.2 on 2021-08-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentpiece', '0030_item_lofi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lofist',
            new_name='LangIns',
        ),
        migrations.RenameField(
            model_name='langins',
            old_name='loi_name',
            new_name='langins_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lofi',
        ),
    ]
