# Generated by Django 2.2 on 2021-06-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
