# Generated by Django 2.2 on 2021-06-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_genre_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(default='c.png', upload_to='media'),
        ),
    ]
