# Generated by Django 2.2 on 2021-06-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0007_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentFlashCard',
        ),
    ]
