# Generated by Django 2.2 on 2021-06-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0008_auto_20210617_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='item_title',
        ),
    ]
