# Generated by Django 2.2 on 2021-06-17 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcard', '0010_auto_20210617_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfc',
            name='fav',
            field=models.ManyToManyField(blank=True, default=None, related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
