# Generated by Django 2.2 on 2021-06-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0011_itemfc_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfc',
            name='article_type',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
