# Generated by Django 2.2 on 2021-07-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0002_item_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='English', max_length=256),
        ),
    ]
