# Generated by Django 2.2 on 2021-07-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0003_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_answer',
            field=models.TextField(default='Your answer', max_length=700),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(max_length=300),
        ),
    ]
