# Generated by Django 2.2 on 2021-07-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0005_item_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='appearance',
            field=models.CharField(default='appear', max_length=300),
        ),
    ]
