# Generated by Django 2.2 on 2021-06-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdib',
            name='thumbnail',
            field=models.ImageField(default='c.png', upload_to='media'),
        ),
    ]
