# Generated by Django 2.2 on 2021-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disboard', '0002_itemdib_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdib',
            name='name',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
