# Generated by Django 2.2 on 2021-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disboard', '0003_itemdib_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdib',
            name='description',
            field=models.CharField(max_length=7000),
        ),
    ]
