# Generated by Django 2.2 on 2021-08-23 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disboard', '0004_auto_20210820_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdib',
            name='item_article',
            field=models.FileField(default='c.png', upload_to='media'),
        ),
        migrations.AddField(
            model_name='itemdib',
            name='item_viewcount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemdib',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemdib',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
    ]
