# Generated by Django 2.2 on 2021-08-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disboard', '0004_auto_20210820_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdib',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
    ]
