# Generated by Django 2.2 on 2021-08-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disboard', '0005_auto_20210823_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdib',
            name='item_article',
        ),
        migrations.RemoveField(
            model_name='itemdib',
            name='item_viewcount',
        ),
    ]
