# Generated by Django 2.2 on 2021-08-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disboard', '0005_auto_20210823_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ViewMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewmode', models.CharField(max_length=100)),
            ],
        ),
    ]
