# Generated by Django 2.2 on 2021-08-23 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disboard', '0006_language_viewmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdib',
            name='article_viewtype',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='disboard.ViewMode'),
        ),
        migrations.AddField(
            model_name='itemdib',
            name='item_viewcount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemdib',
            name='loi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='disboard.Language'),
        ),
        migrations.AddField(
            model_name='itemdib',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
