# Generated by Django 2.2 on 2021-08-23 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disboard', '0007_auto_20210823_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdib',
            name='article_viewtype',
        ),
        migrations.RemoveField(
            model_name='itemdib',
            name='loi',
        ),
    ]
