# Generated by Django 2.2 on 2021-06-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('suggestion_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YourAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(max_length=300)),
                ('suggestion', models.CharField(blank=True, max_length=256)),
                ('answer', models.CharField(default=1, max_length=20)),
                ('category', models.CharField(blank=True, default=None, max_length=256)),
                ('feedback1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdb1', to='dtt.Feedback')),
                ('feedback2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdb2', to='dtt.Feedback')),
                ('feedback3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdb3', to='dtt.Feedback')),
                ('option1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt1', to='dtt.Option')),
                ('option2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt2', to='dtt.Option')),
                ('option3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt3', to='dtt.Option')),
            ],
        ),
    ]
