# Generated by Django 2.2 on 2021-06-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(default='c.png', upload_to='media'),
        ),
    ]
