# Generated by Django 2.2 on 2021-06-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtt', '0002_item_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.CharField(max_length=500),
        ),
    ]
