# Generated by Django 2.2 on 2021-07-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtt', '0003_auto_20210629_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='answer_count',
            field=models.IntegerField(default=1),
        ),
    ]
