# Generated by Django 2.2 on 2021-07-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtt', '0004_item_answer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.CharField(max_length=300),
        ),
    ]
