# Generated by Django 2.2 on 2021-09-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_itemvid_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_article_name', models.CharField(max_length=500)),
                ('comment_article', models.TextField(max_length=900)),
            ],
        ),
    ]
