# Generated by Django 2.2 on 2021-09-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_comreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='comreview',
            name='comment_user',
            field=models.CharField(default='Commp', max_length=300),
        ),
    ]
