# Generated by Django 2.2 on 2021-08-14 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Price_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Itemfreecon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('item_description', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(default='c.png', upload_to='media')),
                ('item_article', models.FileField(upload_to='media')),
                ('article_type', models.CharField(blank=True, default=None, max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('language_of_instruction', models.CharField(default='English', max_length=100)),
                ('item_viewcount', models.IntegerField(default=1)),
                ('article_viewtype', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='freecon.Genre')),
                ('favre', models.ManyToManyField(blank=True, default=None, related_name='favre', to=settings.AUTH_USER_MODEL)),
                ('item_pricecategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freecon.Price_Category')),
                ('topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='freecon.Category')),
                ('user_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField(default=None, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='freecon.Itemfreecon')),
            ],
        ),
    ]
